// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKkvMJYh-Vxnq1AaVXm0O8OqmRxbJnuzs',
    appId: '1:56219149007:web:a0589a550b789a3e240dba',
    messagingSenderId: '56219149007',
    projectId: 'learnflow-ai-1d3f0',
    authDomain: 'learnflow-ai-1d3f0.firebaseapp.com',
    storageBucket: 'learnflow-ai-1d3f0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWIhFcy4oirvN2HeZrSs4T7lm2SZoeDY0',
    appId: '1:56219149007:android:4f318d7c0afbd965240dba',
    messagingSenderId: '56219149007',
    projectId: 'learnflow-ai-1d3f0',
    storageBucket: 'learnflow-ai-1d3f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoj8a0UC76-4bMwJCIJ5ghbwmerkbjwFc',
    appId: '1:56219149007:ios:973d3f973b790ad7240dba',
    messagingSenderId: '56219149007',
    projectId: 'learnflow-ai-1d3f0',
    storageBucket: 'learnflow-ai-1d3f0.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoj8a0UC76-4bMwJCIJ5ghbwmerkbjwFc',
    appId: '1:56219149007:ios:973d3f973b790ad7240dba',
    messagingSenderId: '56219149007',
    projectId: 'learnflow-ai-1d3f0',
    storageBucket: 'learnflow-ai-1d3f0.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKkvMJYh-Vxnq1AaVXm0O8OqmRxbJnuzs',
    appId: '1:56219149007:web:f5e58dbe6f17ed79240dba',
    messagingSenderId: '56219149007',
    projectId: 'learnflow-ai-1d3f0',
    authDomain: 'learnflow-ai-1d3f0.firebaseapp.com',
    storageBucket: 'learnflow-ai-1d3f0.firebasestorage.app',
  );
}
